### ISSUE TITLE
Query generation throws exception when dynamically creating object

### ISSUE THREAD

**Issue by mtinnes** [couchbaselabs/Linq2Couchbase#142]
Dynamic object creation seems to be failing during query generation. This piece of code throws `Object reference not set to an instance of an object.` fails when the expression is evaluated:
```
var q = from pl in pinglogs.Query<SupportLib.Couchbase.PingLog>()
                        where pl.InternalId == id
                        orderby pl.Timestamp descending
                        //select pl;
                select new
                {
                    DeviceId = pl.InternalId,
                    PingTime = new DateTime(pl.Timestamp), // <-- this line is causing the crash
                    PingTypeId = pl.Type,
                    PingType = pl.Type
                };
                var ping = q.Take(5).ToList();
`


Stack trace:
```
```
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.VisitNewObject(IList`1 members, IList`1 arguments)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.VisitNew(NewExpression expression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.Visit(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.VisitSelectNewExpression(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.GetN1QlSelectNewExpression(Expression expression, N1QlQueryGenerationContext queryGenerationContext)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.GetSelectParameters(SelectClause selectClause, QueryModel queryModel)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection(QueryModel queryModel, Boolean selectDocumentMetadata, ScalarResultBehavior& scalarResultBehavior)
   at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by brantburnett** [comment]
@mtinnes 

That approach to handling DateTime values isn't how the the LINQ library is designed.  To use DateTime's:

1.  Make sure they are ISO 8601 formatted strings in Javascript (this is normally true)
2.  Just make the property on the POCO PingLog class a DateTime type

If you do that, everything is handled automatically for you.  Note that if you're indexing on the Timestamp property, you want to actually index on the function STR_TO_MILLIS(timestamp).  For more information see the last comment from me on #111.

Brant

**Comment by mtinnes** [comment]
Thanks Brant, I had converted the field to millis in order to speed indexing - was not aware of the ability to index on a function. Thanks
