### ISSUE TITLE
Expected "DistinctScan" but was "PrimaryScan3" in AnyNestedArrayWithFilter_UsesArrayIndex

### ISSUE THREAD

**Issue by jeffrymorris** [couchbaselabs/Linq2Couchbase#349]
When running the AnyNestedArrayWithFilter_UsesArrayIndex test in Couchbase.LinkIntergrationTests the folling failure is encountered:

```
String lengths are both 12. Strings differ at index 0.
  Expected: "DistinctScan"
  But was:  "PrimaryScan3"
  -----------^

   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Couchbase.Linq.IntegrationTests.AnyAllTests.AnyNestedArrayWithFilter_UsesArrayIndex() in C:\Users\Jeff Morris\source\Linq2Couchbase\Src\Couchbase.Linq.IntegrationTests\AnyAllTests.cs:line 48
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 95
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in D:\a\1\s\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 58
```

This failure occurs in both Couchbase Server 3.0.7 and 3.2.0.

Jeff

**Comment by brantburnett** [comment]
Is this index created? https://github.com/couchbaselabs/Linq2Couchbase/blob/c3fa270753e5508453e1ec15e15f994b9212c2a7/Src/Couchbase.Linq.IntegrationTests/AnyAllTests.cs#L36

**Comment by jeffrymorris** [comment]
@brantburnett - I missed that - yes works once created. Looks like the cause is related to: https://github.com/couchbaselabs/Linq2Couchbase/issues/348

Thanks,
jeff
