### ISSUE TITLE
Couchbase.Core.Exceptions.IndexFailureException raised when calling LongCountAsync()

### ISSUE THREAD

**Issue by amaruj** [couchbaselabs/Linq2Couchbase#368]
Hello,

I sometimes get an exception when I call : 

`long size = await queryable.LongCountAsync(CancellationToken.None).ConfigureAwait(false);`

### Exception :
```
Couchbase.Core.Exceptions.IndexFailureException
Failed to get count for keyspace default:ot_cibml - cause: write tcp 10.118.180.31:49586->10.118.185.14:11210: write: connection timed out [12006]
   at Couchbase.Query.QueryResultExtensions.ThrowExceptionOnError[T](IQueryResult`1 result, QueryErrorContext context)
   at Couchbase.Query.StreamingQueryResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Couchbase.Query.StreamingQueryResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Couchbase.Linq.Execution.ClusterQueryExecutor.ExecuteCollectionAsync[T](String statement, LinqQueryOptions queryOptions, CancellationToken cancellationToken)+MoveNext()
   at Couchbase.Linq.Execution.ClusterQueryExecutor.ExecuteCollectionAsync[T](String statement, LinqQueryOptions queryOptions, CancellationToken cancellationToken)+MoveNext()
   at Couchbase.Linq.Execution.ClusterQueryExecutor.ExecuteCollectionAsync[T](String statement, LinqQueryOptions queryOptions, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<SingleAsync>g__Core|530_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Single.cs:line 50
   at System.Linq.AsyncEnumerable.<SingleAsync>g__Core|530_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Single.cs:line 55
   at Orbit.Common.DataAccess.Couchbase.Tests.Integration.CouchbaseAccessorGetSizeAsyncTests.CouchbaseAccessor_GetSizeAsync_WhenCollectionIsNotEmpty_ShouldReturnStrictlyPositiveSize() in C:\Users\UT32GV\source\repos\orbit-services\Orbit\Orbit.Common.DataAccess.Couchbase.Tests.Integration\CouchbaseAccessorGetSizeAsyncTests.cs:line 52
```

### Here is what I can see into the logs :
[2023-09-01 12:12:33Z] dbug: Couchbase.Linq.QueryGeneration.QueryPartsAggregator[0]
      SELECT RAW COUNT(*) FROM `ot_cibml`.`_default`.`accessor_integration_tests` as `Extent1`
[2023-09-01 12:12:33Z] dbug: Couchbase.Linq.Execution.ClusterQueryExecutor[0]
      Generated query: SELECT RAW COUNT(*) FROM `ot_cibml`.`_default`.`accessor_integration_tests` as `Extent1`
[2023-09-01 12:12:33Z] dbug: Couchbase.Query.QueryClient[0]
      Sending query 8a8775a8-8a99-4b97-8d06-14258bf648c8 to node http://cmxd4o05.dev.cm.par.emea.cib:8093/query/service.
[2023-09-01 12:12:33Z] dbug: Couchbase.Query.QueryClient[0]
      Request 8a8775a8-8a99-4b97-8d06-14258bf648c8 has succeeded.
[2023-09-01 12:12:33Z] dbug: Couchbase.Query.QueryClient[0]
      The request 8a8775a8-8a99-4b97-8d06-14258bf648c8 failed because: Failed to get count for keyspace default:ot_cibml - cause: write tcp 10.118.180.31:49586->10.118.185.14:11210: write: connection timed out [12006]

**Comment by brantburnett** [comment]
This appears to be a problem in your network infrastructure or the servers, that error is for a network timeout between the Couchbase Query note and the Couchbase Data node, not something within the SDK.

If you are a supported Couchbase customer, you could open a support ticket. You might also try asking about this in the Couchbase forums at https://www.couchbase.com/forums/c/couchbase-server/15.
