### ISSUE TITLE
Projection to strong types

### ISSUE THREAD

**Issue by wiciul** [couchbaselabs/Linq2Couchbase#85]
If it would be possible it would be great to have possibility to project to strong and not only anonymous types.

**Comment by brantburnett** [comment]
@wiciul 

Can you send some example code that is not working.  It should function as long as you are using the default constructor (no parameters) and then assigning values in a { ... } block.

Brant

**Comment by wiciul** [comment]
var logEntry = _unresolvedCoverageLogContext
                .Query<UnresolvedCoverageLogEntry>()
                .Where(e => e.Type == "Reuters.Tornado.unresolvedcoverage.addUnresolvedCoverageRequest")
                .Select(e => new AddUnresolvedCoverageRequest
                {
                    Date = e.Date
                }).ToList();


Type : System.NotSupportedException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : The expression 'new AddUnresolvedCoverageRequest() {Date = [e].Date}' (type: System.Linq.Expressions.MemberInitExpression) is not supported by this LINQ provider.
Source : Remotion.Linq
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : TResult VisitUnhandledItem[TItem,TResult](TItem, System.String, System.Func`2[TItem,TResult])
HResult : -2146233067
Stack Trace :    at Remotion.Linq.Parsing.ThrowingExpressionTreeVisitor.VisitUnhandledItem[TItem,TResult](TItem unhandledItem, String visitMethod, Func`2 baseBehavior)
   at Remotion.Linq.Parsing.ThrowingExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.VisitExpression(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlExpressionTreeVisitor.GetN1QlExpression(Expression expression, N1QlQueryGenerationContext queryGenerationContext)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.GetN1QlExpression(Expression expression)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.GetSelectParameters(SelectClause selectClause, QueryModel queryModel)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Couchbase.Linq.QueryGeneration.N1QlQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Couchbase.Linq.BucketQueryExecutor.ExecuteCollection(QueryModel queryModel, Boolean& resultExtractionRequired)
   at Couchbase.Linq.BucketQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MDBS.MDBSW.Areas.PreAnalyst.Api.AddUnresolvedCoverageRequestsController.Get() in c:\data\._svn\dbs2\trunk\mdbs\MDBSW\Areas\PreAnalyst\Api\AddUnresolvedCoverageRequestsController.cs:line 41
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by brantburnett** [comment]
Okay, yeah that's a miss on our part in our testing.  I'll see if I can get that addressed.

Thanks!

**Comment by wiciul** [comment]
Would be good if it could be fixed quickly:) This is somehow blocking for us. Thanks.

**Comment by brantburnett** [comment]
@wiciul 

I've completed work to add support for your use case.  @jeffrymorris is planning on pulling it in tomorrow or this weekend and releasing 1.0.3 with this improvement.  If you'd like to see the work or make a build yourself, it's available in my repository:

https://github.com/brantburnett/Linq2Couchbase/tree/issue85-strongtypeprojections

Thanks,
Brant

**Comment by wiciul** [comment]
@brantburnett 

I have built your repository. Can confirm it works. Waiting for nuget 1.0.3. Thanst for quick fix.

**Comment by jeffrymorris** [comment]
@wiciul -

Heads up that 1.0.3 is scheduled for release the 3rd week of January, so you'll see the NuGet packages at that time.

-Jeff

**Comment by jeffrymorris** [comment]
See https://github.com/couchbaselabs/Linq2Couchbase/commit/64d180dc2ec9aab98738db38a9a6624344694f1f
